[common]
platform = espressif32
framework = arduino
monitor_speed = 115200

[env:sensor]
platform = ${common.platform}
framework = ${common.framework}
board = esp32dev
monitor_speed = ${common.monitor_speed}
upload_port = COM8
monitor_port = COM8
build_src_filter = +<sensor/>
lib_deps =
    bblanchon/ArduinoJson@^7.0.4
    links2004/WebSockets@^2.4.1

[env:cam]
platform = ${common.platform}
framework = ${common.framework}
board = esp32cam
monitor_speed = ${common.monitor_speed}
board_build.partitions = huge_app.csv
build_src_filter = +<cam/>